---

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: import vpc variables
      include_vars: vars/vpc_setup

    - name: create devops vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    
    - debug:
        var: vpcout

    - name: Create Public Subnet 1 in Zone
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: devops-pubsub1
      register: pubsub1_out

    - debug:
        var: pubsub1_out